<?php 
require_once("include/portal/header.php");
?>
   
<?php 
require_once("include/portal/topbar.php");
?>
<?php 
require_once("include/portal/nav.php");
?>
<?php 
require_once("pages/portal/top_vg.php");
?>
<?php 
require_once("pages/portal/about.php");
?>
<?php 
require_once("pages/portal/service.php");
?>
<?php 
require_once("pages/portal/facts.php");
?>
<?php 
require_once("pages/portal/causes.php");
?>
<?php 
require_once("pages/portal/donate.php");
?>
<?php 
require_once("pages/portal/event.php");
?>
<?php 
require_once("pages/portal/team.php");
?>
<?php 
require_once("pages/portal/volunteer.php");
?>
<?php 
require_once("pages/portal/testimonial.php");
?>
<?php 
require_once("pages/portal/contact.php");
?>
<?php 
require_once("pages/portal/blog.php");
?>   
<?php 
require_once("include/portal/footer.php");
?>

    